db_mysql:
  image: mysql:5.6
  ports      :
    - "3306:3306"
  environment:
    MYSQL_DATABASE     : appdb
    MYSQL_ROOT_PASSWORD: mysql_root_pass
    MYSQL_USER         : mysql_user
    MYSQL_PASSWORD     : mysql_pass
  volumes:
    - "./mysql-dat:/etc/mysql/conf.d"
    - "./db:/var/lib/mysql"

node:
  env_file:
    .env
  build      : "./nodejs"
  working_dir: "/app"  
  links:
  - db_mysql    
  volumes:
    - "./server:/app"
  command: "nodemon --config nodemon.json index.js"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./data/logs/nginx/:/var/log/nginx
    - ./certbot/certs/:/var/certs
  volumes_from:
    - node
  links:
    - node:node

certbot:
  build: "./certbot"
  links:    
    - nginx
  environment:
    - CN=example.com
    - EMAIL=fake@gmail.com
  volumes:
    - ./certbot/letsencrypt/:/var/www/letsencrypt
    - ./certbot/certs/:/var/certs